-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Brand" ADD VALUE 'CHEVROLET';
ALTER TYPE "Brand" ADD VALUE 'FORD';
ALTER TYPE "Brand" ADD VALUE 'HONDA';
ALTER TYPE "Brand" ADD VALUE 'HYUNDAI';
ALTER TYPE "Brand" ADD VALUE 'MITSUBISHI';
ALTER TYPE "Brand" ADD VALUE 'JEEP';
ALTER TYPE "Brand" ADD VALUE 'CHRYSLER';
ALTER TYPE "Brand" ADD VALUE 'DODGE';
ALTER TYPE "Brand" ADD VALUE 'RAM';
ALTER TYPE "Brand" ADD VALUE 'BUICK';
ALTER TYPE "Brand" ADD VALUE 'CADILLAC';
ALTER TYPE "Brand" ADD VALUE 'LINCOLN';
ALTER TYPE "Brand" ADD VALUE 'MERCURY';
ALTER TYPE "Brand" ADD VALUE 'PONTIAC';
ALTER TYPE "Brand" ADD VALUE 'HUMMER';
ALTER TYPE "Brand" ADD VALUE 'VOLKSWAGEN';
ALTER TYPE "Brand" ADD VALUE 'AUDI';
ALTER TYPE "Brand" ADD VALUE 'BMW';
ALTER TYPE "Brand" ADD VALUE 'MERCEDES_BENZ';
ALTER TYPE "Brand" ADD VALUE 'PORSCHE';
ALTER TYPE "Brand" ADD VALUE 'MINI';
ALTER TYPE "Brand" ADD VALUE 'FIAT';
ALTER TYPE "Brand" ADD VALUE 'ALFA_ROMEO';
ALTER TYPE "Brand" ADD VALUE 'RENAULT';
ALTER TYPE "Brand" ADD VALUE 'PEUGEOT';
ALTER TYPE "Brand" ADD VALUE 'CITROEN';
ALTER TYPE "Brand" ADD VALUE 'SEAT';
ALTER TYPE "Brand" ADD VALUE 'SKODA';
ALTER TYPE "Brand" ADD VALUE 'ASTON_MARTIN';
ALTER TYPE "Brand" ADD VALUE 'LAND_ROVER';
ALTER TYPE "Brand" ADD VALUE 'CHERY';
ALTER TYPE "Brand" ADD VALUE 'BYD';
ALTER TYPE "Brand" ADD VALUE 'GEELY';
ALTER TYPE "Brand" ADD VALUE 'GREAT_WALL';
ALTER TYPE "Brand" ADD VALUE 'JAC';
ALTER TYPE "Brand" ADD VALUE 'JMC';
ALTER TYPE "Brand" ADD VALUE 'LIFAN';
ALTER TYPE "Brand" ADD VALUE 'WULING';
ALTER TYPE "Brand" ADD VALUE 'ZHONGXING';
ALTER TYPE "Brand" ADD VALUE 'ZOTYE';
ALTER TYPE "Brand" ADD VALUE 'HAFEI';
ALTER TYPE "Brand" ADD VALUE 'CHANA';
ALTER TYPE "Brand" ADD VALUE 'CHANGHE';
ALTER TYPE "Brand" ADD VALUE 'VENIRAUTO';
ALTER TYPE "Brand" ADD VALUE 'VIT';
ALTER TYPE "Brand" ADD VALUE 'DONGFENG';
ALTER TYPE "Brand" ADD VALUE 'FORTHING';
ALTER TYPE "Brand" ADD VALUE 'FOTON';
ALTER TYPE "Brand" ADD VALUE 'ISUZU';
ALTER TYPE "Brand" ADD VALUE 'IVECO';
ALTER TYPE "Brand" ADD VALUE 'MACK';
