export enum AnalyticsEventType {
  VEHICLE_VIEWED = 'VEHICLE_VIEWED',
  VEHICLE_ADDED_TO_COMPARISON = 'VEHICLE_ADDED_TO_COMPARISON',
  COMPARISON_PERFORMED = 'COMPARISON_PERFORMED',
  QUIZ_COMPLETED = 'QUIZ_COMPLETED',
  LEAD_SUBMITTED = 'LEAD_SUBMITTED',
}
