export enum Brand {
  TOYOTA = 'TOYOTA',
  KIA = 'KIA',
  CHANGAN = 'CHANGAN',
  CHEVROLET = 'CHEVROLET',
  FORD = 'FORD',
  HONDA = 'HONDA',
  HYUNDAI = 'HYUNDAI',
  MITSUBISHI = 'MITSUBISHI',
  JEEP = 'JEEP',
  CHRYSLER = 'CHRYSLER',
  DODGE = 'DODGE',
  RAM = 'RAM',
  BUICK = 'BUICK',
  CADILLAC = 'CADILLAC',
  LINCOLN = 'LINCOLN',
  MERCURY = 'MERCURY',
  PONTIAC = 'PONTIAC',
  HUMMER = 'HUMMER',
  VOLKSWAGEN = 'VOLKSWAGEN',
  AUDI = 'AUDI',
  BMW = 'BMW',
  MERCEDES_BENZ = 'MERCEDES_BENZ',
  PORSCHE = 'PORSCHE',
  MINI = 'MINI',
  FIAT = 'FIAT',
  ALFA_ROMEO = 'ALFA_ROMEO',
  RENAULT = 'RENAULT',
  PEUGEOT = 'PEUGEOT',
  CITROEN = 'CITROEN',
  SEAT = 'SEAT',
  SKODA = 'SKODA',
  ASTON_MARTIN = 'ASTON_MARTIN',
  LAND_ROVER = 'LAND_ROVER',
  CHERY = 'CHERY',
  BYD = 'BYD',
  GEELY = 'GEELY',
  GREAT_WALL = 'GREAT_WALL',
  JAC = 'JAC',
  JMC = 'JMC',
  LIFAN = 'LIFAN',
  WULING = 'WULING',
  ZHONGXING = 'ZHONGXING',
  ZOTYE = 'ZOTYE',
  HAFEI = 'HAFEI',
  CHANA = 'CHANA',
  CHANGHE = 'CHANGHE',
  VENIRAUTO = 'VENIRAUTO',
  VIT = 'VIT',
  DONGFENG = 'DONGFENG',
  FORTHING = 'FORTHING',
  FOTON = 'FOTON',
  ISUZU = 'ISUZU',
  IVECO = 'IVECO',
  MACK = 'MACK',
}

export enum VehicleCategory {
  SUV = 'SUV',
  SEDAN = 'SEDAN',
  PICKUP = 'PICKUP',
  HATCHBACK = 'HATCHBACK',
  COMPACTO = 'COMPACTO',
}

export enum FuelType {
  GASOLINA = 'GASOLINA',
  DIESEL = 'DIESEL',
  HIBRIDO = 'HIBRIDO',
  ELECTRICO = 'ELECTRICO',
}

export enum TransmissionType {
  MANUAL = 'MANUAL',
  AUTOMATICA = 'AUTOMATICA',
  CVT = 'CVT',
  DCT = 'DCT',
}

export enum DriveType {
  FWD_4X2 = 'FWD_4X2',
  AWD_4X4 = 'AWD_4X4',
}

export enum FuelEconomyUnit {
  KM_POR_GAL = 'KM_POR_GAL',
  L_POR_100KM = 'L_POR_100KM',
}
